baseurl: /github_pages

defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "posts" # previously
        values:
            layout: "default"